name: My First Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Show files
        run: ls

      - name: Validate HTML
        run: echo "Checking HTML files..."

      - name: Run Test
        run: |
          echo "Running tests..."
          exit 1