name: Docker CI Pipeline

on:
  push:
    branches:
      - main
      - feature-docker-cicd

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build docker image
        run: docker build -t devops-app .